name: main
on:
  workflow_dispatch: {}
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4.0.3
      - name: main
        id: main
        run: npx repolinter lint
